"""init: db

Revision ID: 11b28ac4b506
Revises: bb71e2bef495
Create Date: 2023-05-13 11:20:50.674689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b28ac4b506'
down_revision = 'bb71e2bef495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
