"""init: db

Revision ID: bb71e2bef495
Revises: c58cb0b5b1d2
Create Date: 2023-05-13 00:24:34.975908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb71e2bef495'
down_revision = 'c58cb0b5b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
