"""init: db

Revision ID: 18153b4c4893
Revises: 11b28ac4b506
Create Date: 2023-05-13 11:23:39.420797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18153b4c4893'
down_revision = '11b28ac4b506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
